VolumeDialog: Check weather DevicePersonalization is installed
@ZeNiXxX

When DevicePersonalization (com.google.android.as) isnt install the Log is spammed with following error:

2020-12-12 10:08:52.009 24469-24511/com.android.systemui E/vol.VolumeDialogControl: isCaptionsServiceEnabled failed to check for captions component
    java.lang.IllegalArgumentException: Unknown component: ComponentInfo{com.google.android.as/com.google.android.apps.miphone.aiai.captions.CaptionsService}
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.content.pm.IPackageManager$Stub$Proxy.getComponentEnabledSetting(IPackageManager.java:6822)
        at android.app.ApplicationPackageManager.getComponentEnabledSetting(ApplicationPackageManager.java:2723)
        at com.android.systemui.volume.VolumeDialogControllerImpl.onGetCaptionsComponentStateW(VolumeDialogControllerImpl.java:448)
        at com.android.systemui.volume.VolumeDialogControllerImpl.access$2000(VolumeDialogControllerImpl.java:93)
        at com.android.systemui.volume.VolumeDialogControllerImpl$W.handleMessage(VolumeDialogControllerImpl.java:871)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.pm.PackageManagerService.getComponentEnabledSetting(PackageManagerService.java:21512)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3223)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4360)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)

Fix that !

Signed-off-by: ZeNiXxX <zenixxx.havoc@gmail.com>