Core: Fix NPE on mTaskId
This NPE happens randomly dont know why...however if task is null get task to get new instance to be sure its not null again...

2021-03-12 08:40:31.100 7757-21041/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #68
    Process: com.android.systemui, PID: 7757
    java.lang.NullPointerException: Attempt to read from field 'int com.android.server.wm.Task.mTaskId' on a null object reference
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivityAsUser(IActivityTaskManager.java:3780)
        at com.android.systemui.statusbar.phone.StatusBar.lambda$startActivityDismissingKeyguard$16(StatusBar.java:3061)
        at com.android.systemui.statusbar.phone.StatusBar.lambda$startActivityDismissingKeyguard$16$StatusBar(Unknown Source:0)
        at com.android.systemui.statusbar.phone.-$$Lambda$StatusBar$fPMIOsYMhFXVKHESAjUObpcgeJM.run(Unknown Source:10)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityRecord.addStartingWindow(ActivityRecord.java:1738)
        at com.android.server.wm.ActivityRecord.showStartingWindow(ActivityRecord.java:5737)
        at com.android.server.wm.ActivityStarter.recycleTask(ActivityStarter.java:1933)
        at com.android.server.wm.ActivityStarter.startActivityInner(ActivityStarter.java:1628)
        at com.android.server.wm.ActivityStarter.startActivityUnchecked(ActivityStarter.java:1522)

Signed-off-by: ZeNiXxX <zenixxx.havoc@gmail.com>