SystemUI: Fix non protected broadcast for USER_PRESENT
2021-01-22 17:50:53.054 32449-32531/? E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.android.systemui, PID: 32449
    java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.USER_PRESENT from pid=32449, uid=10237
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5576)
        at android.app.ContextImpl.sendBroadcastAsUser(ContextImpl.java:1290)
        at android.content.ContextWrapper.sendBroadcastAsUser(ContextWrapper.java:545)
        at com.android.systemui.keyguard.KeyguardViewMediator.lambda$sendUserPresentBroadcast$2(KeyguardViewMediator.java:1811)
        at com.android.systemui.keyguard.KeyguardViewMediator.lambda$sendUserPresentBroadcast$2$KeyguardViewMediator(Unknown Source:0)
        at com.android.systemui.keyguard.-$$Lambda$KeyguardViewMediator$D0hsCCxTp4AHvBc22-UzBpCE55U.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16076)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15934)
        at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:16754)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2294)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2881)
2021-01-22 17:51:00.538 768-801/? E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1

Signed-off-by: ZeNiXxX <zenixxx.havoc@gmail.com>